# Set a plain language title for the site.
title: Market Mercury

# Write a short description for the site. This is used for "meta description."
description: A tool for assessing the current temperature of the market based on an investor's perspective

# Set the language for the site. Used for "html lang." Default is English.
lang: en

# Add Google Analytics if needed. Replace placeholder with site ID.
ga: UA-XXXXX-Y

# Avoid GitHub API authentication when building locally. (Not working)
github: [metadata]